name: flutter_splash_login_signup
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  google_fonts: ^2.2.0
  humanitarian_icons: ^1.0.2
  settings_ui: ^2.0.2
  rflutter_alert: ^1.0.2
  dropdown_button2: ^1.1.1
  http: ^0.13.3
  gradient_widgets: ^0.6.0
  new_gradient_app_bar: ^0.1.4
  pin_code_fields: ^7.3.0
  sms_otp_auto_verify: ^2.1.0
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  geolocator: ^8.0.5
  avatar_view: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  passwordfield: ^0.1.0
  intl: ^0.17.0
  intl_phone_field: ^2.1.0
  dropdown_formfield: ^0.1.4
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^5.3.1


flutter_icons:
  andoird: true
  ios: false
  image_path: "images/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/app_logo.png
     - images/logo1.png
     - images/fire.png
     - images/cng.png
     - images/smoke.png
     - images/sound.png
     - images/temp.png
     - images/drawer.jpg
     - images/dp.jpg
     - images/staysafe.jpeg
     - images/dont1.jpg
     - images/dont2.jpg
     - images/dont3.jpg
     - images/dont4.jpg
     - images/dos1.jpg
     - images/dos2.jpg
     - images/dos3.jpg
     - images/dos4.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
